### ISSUE TITLE
Error in importing in python

### ISSUE THREAD

**Issue by Hadi1374** [greatscottgadgets/gr-bluetooth#15]
Hi,
I'm trying to "import gr_bluetooth" in python and I've done the build process. I'm getting this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gr_bluetooth/__init__.py", line 45, in <module>
    from gr_bluetooth import *
  File "/usr/local/lib/python2.7/dist-packages/gr_bluetooth/gr_bluetooth.py", line 17, in <module>
    _gr_bluetooth = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/gr_bluetooth/gr_bluetooth.py", line 16, in swig_import_helper
    return importlib.import_module('_gr_bluetooth')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _gr_bluetooth

**Comment by samcrow** [comment]
i had the same problem when trying to import gr_bluetooth just after installing it. Running `sudo ldconfig` fixed the problem.
