### ISSUE TITLE
Crash in sniffer during multi_block::channel_samples

### ISSUE THREAD

**Issue by Javantea** [greatscottgadgets/gr-bluetooth#8]
```
btrx -f 2476M -S
gr-osmosdr v0.1.4-48-g86ad5842 (0.1.5git) gnuradio 3.7.8
built-in source types: file fcd rtl rtl_tcp hackrf rfspace
Using HackRF One with firmware 2015.07.2
Using Volk machine: sse4_2_64_orc
history set to 1651 samples: channel=21, noise=401
Segmentation fault (core dumped)
```

On the second iteration of complex_to_mag_squared::make in multi_block::channel_samples, malloc (called by new) segfaults.

**Comment by Javantea** [comment]
Stack trace on my modified version of gr-bluetooth without debugging symbols.
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fd2077fe700 (LWP 4899)]
0x00007fd21ca45ca9 in _int_malloc () from /lib64/libc.so.6
(gdb) bt
#0  0x00007fd21ca45ca9 in _int_malloc () from /lib64/libc.so.6
#1  0x00007fd21ca478ee in malloc () from /lib64/libc.so.6
#2  0x00007fd219aead7d in operator new(unsigned long) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/libstdc++.so.6
#3  0x00007fd219b45e29 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/libstdc++.so.6
#4  0x00007fd219b47551 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/libstdc++.so.6
#5  0x00007fd219b47968 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.5/libstdc++.so.6
#6  0x00007fd212e77039 in gr::blocks::complex_to_mag_squared_impl::complex_to_mag_squared_impl(unsigned long) ()
   from /usr/local/lib64/libgnuradio-blocks-3.7.8.so.0.0.0
#7  0x00007fd212e77166 in gr::blocks::complex_to_mag_squared::make(unsigned long) ()
   from /usr/local/lib64/libgnuradio-blocks-3.7.8.so.0.0.0
#8  0x00007fd20fd43b70 in gr::bluetooth::multi_block::channel_samples(double, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&, double&, int) () from /usr/local/lib64/libgnuradio-bluetooth.so
#9  0x00007fd20fd4afaa in gr::bluetooth::multi_sniffer_impl::work(int, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) () from /usr/local/lib64/libgnuradio-bluetooth.so
#10 0x00007fd21b327d47 in gr::sync_block::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) ()
   from /usr/local/lib64/libgnuradio-runtime-3.7.8.so.0.0.0
#11 0x00007fd21b2f6525 in gr::block_executor::run_one_iteration() ()
   from /usr/local/lib64/libgnuradio-runtime-3.7.8.so.0.0.0
#12 0x00007fd21b32f3ac in gr::tpb_thread_body::tpb_thread_body(boost::shared_ptr<gr::block>, int) ()
   from /usr/local/lib64/libgnuradio-runtime-3.7.8.so.0.0.0
#13 0x00007fd21b325731 in boost::detail::function::void_function_obj_invoker0<gr::thread::thread_body_wrapper<gr::tpb_container>, void>::invoke(boost::detail::function::function_buffer&) ()
   from /usr/local/lib64/libgnuradio-runtime-3.7.8.so.0.0.0
#14 0x00007fd21b2deb90 in boost::detail::thread_data<boost::function0<void> >::run() ()
   from /usr/local/lib64/libgnuradio-runtime-3.7.8.so.0.0.0
#15 0x00007fd21a5a8aba in thread_proxy () from /usr/lib64/libboost_thread.so.1.57.0
#16 0x00007fd21cd6c204 in start_thread () from /lib64/libpthread.so.0
#17 0x00007fd21cab33ad in clone () from /lib64/libc.so.6
```

**Comment by GoTN** [comment]
I got the same error for every block. But it seems to appear randomly because sometimes the command:
btrx -f 2476M -i headset2.cfile
crashes, sometimes it doesn't. And only headset3.cfile gives me the LAP. All other files (with the commands given in manifest.txt) just finish without any output.

**Comment by straithe** [comment]
@GoTN Are you still experiencing this issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
